/* COM-014 — proves the Finance listener on comercial.opportunity-won: it creates a
 * projected INCOME Commitment from the event PAYLOAD ONLY (never reads Comercial tables),
 * dates it dueDate = occurredAt + paymentTermDays using the @db.Date-safe UTC convention
 * (pinned across a year boundary), dedupes a re-delivered event (RETURN, no duplicate),
 * skips gracefully when auto-commitments are off or no fiscal period exists, and lets a
 * genuine create failure THROW (so DomainEventsService marks it FAILED and the retry cron
 * fires). Stateful fakes, mirroring service-order-handoff.listener.spec.ts. */
import { ComercialOpportunityWonEvent } from '../operations/events/domain-event-types';
import { OpportunityCommitmentListener } from './opportunity-commitment.listener';

type Any = Record<string, unknown>;

const baseEvent = (
  extra: Partial<ComercialOpportunityWonEvent> = {},
): ComercialOpportunityWonEvent => ({
  type: 'comercial.opportunity-won',
  companyId: 'c1',
  occurredAt: '2026-12-20T09:30:00.000Z', // near a YEAR boundary to prove the date math
  opportunityId: 'opp1',
  quoteId: 'q1',
  clientName: 'Minera Los Andes SpA',
  counterpartyId: 'cp1',
  title: 'Servicio de aseo faena norte',
  description: 'notas',
  scopeLines: [{ serviceName: 'Aseo mensual', quantity: 2, unitPrice: 10000, lineTotal: 20000 }],
  netAmount: 20000,
  taxAmount: 3800,
  totalAmount: 23800,
  currency: 'CLP',
  ownerId: 'owner1',
  paymentTermDays: 30,
  ...extra,
});

function makeListener(
  opts: {
    existing?: Any | null;
    period?: Any | null;
    autoCommitments?: boolean;
    createThrows?: boolean;
  } = {},
) {
  const commitmentFindFirst = jest.fn(() => Promise.resolve(opts.existing ?? null));
  const commitmentCreate = jest.fn((args: Any) => {
    if (opts.createThrows) return Promise.reject(new Error('db down'));
    return Promise.resolve({ id: 'com1', ...(args.data as Any) });
  });
  const fiscalPeriodFindFirst = jest.fn(() =>
    Promise.resolve(opts.period === undefined ? { id: 'fp1' } : opts.period),
  );
  // Present ONLY so the payload-only test can prove they are NEVER called.
  const opportunityFindFirst = jest.fn(() => Promise.resolve(null));
  const quoteFindFirst = jest.fn(() => Promise.resolve(null));

  const tx = { commitment: { create: commitmentCreate } };
  const prisma = {
    commitment: { findFirst: commitmentFindFirst },
    fiscalPeriod: { findFirst: fiscalPeriodFindFirst },
    opportunity: { findFirst: opportunityFindFirst },
    quote: { findFirst: quoteFindFirst },
  } as unknown as ConstructorParameters<typeof OpportunityCommitmentListener>[0];
  const rls = {
    executeWithRls: (_c: string, _u: string | null, fn: (t: unknown) => unknown) => fn(tx),
  } as unknown as ConstructorParameters<typeof OpportunityCommitmentListener>[1];
  const alertSettings = {
    getOrCreate: jest.fn(() =>
      Promise.resolve({ enableAutoCommitments: opts.autoCommitments ?? true }),
    ),
  } as unknown as ConstructorParameters<typeof OpportunityCommitmentListener>[2];

  return {
    listener: new OpportunityCommitmentListener(prisma, rls, alertSettings),
    commitmentFindFirst,
    commitmentCreate,
    fiscalPeriodFindFirst,
    opportunityFindFirst,
    quoteFindFirst,
  };
}

describe('OpportunityCommitmentListener — projected income commitment', () => {
  it('creates an INCOME commitment; dueDate = occurredAt + paymentTermDays (UTC date-only, crosses year boundary)', async () => {
    const { listener, commitmentCreate, fiscalPeriodFindFirst } = makeListener();
    const res = (await listener.handleOpportunityWon(baseEvent())) as Any;

    expect(commitmentCreate).toHaveBeenCalledTimes(1);
    const data = (commitmentCreate.mock.calls[0][0] as Any).data as Any;

    expect(data.type).toBe('INCOME');
    // 2026-12-20 (anchored to 00:00 UTC) + 30d = 2027-01-19 00:00 UTC — no time component,
    // no off-by-one, correct month/year rollover.
    expect((data.dueDate as Date).toISOString()).toBe('2027-01-19T00:00:00.000Z');
    // amount = GROSS total (net + IVA) — the cash actually collected from the client.
    expect(String(data.amount)).toBe('23800');
    expect(data.currency).toBe('CLP');
    expect(data.counterpartyId).toBe('cp1'); // carried from the payload
    expect(data.categoryId).toBeNull(); // no income template in V1
    expect(data.status).toBe('PENDING');
    expect(data.sourceType).toBe('comercial_opportunity_won');
    expect(data.sourceId).toBe('opp1');
    expect(data.isAutoGenerated).toBe(true);
    expect(data.description).toContain('30 días');

    // The fiscal period is looked up for the DUE month/year (2027-01), not the handoff month.
    expect(fiscalPeriodFindFirst).toHaveBeenCalledWith(
      expect.objectContaining({ where: expect.objectContaining({ year: 2027, month: 1 }) }),
    );
    expect(res.commitmentId).toBe('com1');
  });

  it('pins date math within the same month too (2026-07-08 + 60d = 2026-09-06)', async () => {
    const { listener, commitmentCreate } = makeListener();
    await listener.handleOpportunityWon(
      baseEvent({ occurredAt: '2026-07-08T23:59:00.000Z', paymentTermDays: 60 }),
    );
    const data = (commitmentCreate.mock.calls[0][0] as Any).data as Any;
    // 2026-07-08 (00:00 UTC) + 60d = 2026-09-06 (late-day time component dropped).
    expect((data.dueDate as Date).toISOString()).toBe('2026-09-06T00:00:00.000Z');
  });

  it('carries counterpartyId=null when the payload has none', async () => {
    const { listener, commitmentCreate } = makeListener();
    await listener.handleOpportunityWon(baseEvent({ counterpartyId: null }));
    const data = (commitmentCreate.mock.calls[0][0] as Any).data as Any;
    expect(data.counterpartyId).toBeNull();
  });

  it('DEDUPES a re-delivered event (same opportunity) — returns skipped, creates nothing', async () => {
    const { listener, commitmentCreate } = makeListener({ existing: { id: 'comX' } });
    const res = (await listener.handleOpportunityWon(baseEvent())) as Any;
    expect(res).toEqual({
      handler: 'comercial-income-commitment',
      skipped: 'commitment exists',
      commitmentId: 'comX',
    });
    expect(commitmentCreate).not.toHaveBeenCalled();
  });

  it('skips (creates nothing) when no fiscal period exists for the due month', async () => {
    const { listener, commitmentCreate } = makeListener({ period: null });
    const res = (await listener.handleOpportunityWon(baseEvent())) as Any;
    expect(res.skipped).toBe('no fiscal period');
    expect(commitmentCreate).not.toHaveBeenCalled();
  });

  it('skips when auto-commitments are disabled company-wide (before touching the DB)', async () => {
    const { listener, commitmentCreate, commitmentFindFirst } = makeListener({
      autoCommitments: false,
    });
    const res = (await listener.handleOpportunityWon(baseEvent())) as Any;
    expect(res.skipped).toBe('auto-commitments disabled');
    expect(commitmentFindFirst).not.toHaveBeenCalled();
    expect(commitmentCreate).not.toHaveBeenCalled();
  });

  it('THROWS on a genuine create failure (so markFailed + retry fire)', async () => {
    const { listener } = makeListener({ createThrows: true });
    await expect(listener.handleOpportunityWon(baseEvent())).rejects.toThrow('db down');
  });

  it('reads ONLY the event payload — never a Comercial table (opportunity/quote)', async () => {
    const { listener, opportunityFindFirst, quoteFindFirst } = makeListener();
    await listener.handleOpportunityWon(baseEvent());
    expect(opportunityFindFirst).not.toHaveBeenCalled();
    expect(quoteFindFirst).not.toHaveBeenCalled();
  });
});
