import { createHash, randomUUID } from 'crypto';
import { Injectable, Logger, NotFoundException, BadRequestException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import archiver from 'archiver';
import JSZip from 'jszip';
import PDFDocument from 'pdfkit';
import { PassThrough } from 'stream';
import { PrismaService } from '../../common/prisma/prisma.service';
import { RlsService } from '../../common/rls/rls.service';
import { StorageService } from '../../common/storage/storage.service';
import { AcknowledgmentCoverageReportGenerator } from '../reports/generators/acknowledgment-coverage.generator';
import { AlertsHistoryReportGenerator } from '../reports/generators/alerts-history.generator';
import { AssetComplianceReportGenerator } from '../reports/generators/asset-compliance-report.generator';
import { WorkPermitsReportGenerator } from '../reports/generators/work-permits.generator';
import { LEGAL_FRAMEWORK_CHILE, REPORT_FILES } from './legal-framework.constant';
import { AssetQrInventoryReportGenerator } from './reports/asset-qr-inventory.report';
import { AssetStatusChangesReportGenerator } from './reports/asset-status-changes.report';
import { ExceptionsAuditReportGenerator } from './reports/exceptions-audit.report';

/* OPS-036 — orchestrates the audit-package generation:
   1. Run the 7 reports (4 from OPS-031, 3 new) — per-report
      try/catch so a single bad report doesn't kill the whole
      package; failed ones are flagged in the manifest and on
      the cover PDF.
   2. Render the cover PDF and the legal-framework PDF.
   3. Build the manifest JSON with SHA-256 of every file.
   4. ZIP everything with predictable filenames.
   5. Persist the row + bytes (MinIO when configured, DB blob
      fallback) and return the AuditPackage record. */

const AUDIT_PACKAGE_BUCKET = process.env.OPERATIONS_BUCKET || 'excelsia-documents';
const PACKAGE_TTL_DAYS = 365;

interface ReportProduce {
  /* Filename inside the ZIP, e.g. "01-cumplimiento-documental.xlsx". */
  fileName: string;
  /* Display label for the cover PDF and manifest. */
  label: string;
  /* Stable code referenced by the legal framework. */
  code: string;
  /* Generated bytes — null when generation failed. */
  buffer: Buffer | null;
  /* Error message captured when buffer is null. */
  error: string | null;
}

export interface ManifestFileEntry {
  name: string;
  sha256: string;
  size: number;
  rowsCount: number | null;
}

export interface AuditPackageManifest {
  version: '1.0';
  auditPackageId: string;
  generatedAt: string;
  generatedBy: { id: string; email: string; name: string };
  company: { id: string; name: string; rut: string | null };
  scope: {
    period: { from: string; to: string };
    locations: 'all' | string[];
    assetTypes: 'all' | string[];
    reason: string;
  };
  files: ManifestFileEntry[];
  packageSignature: string;
  dataSnapshot: DataSnapshot;
  framework: string[];
  failedReports: Array<{ name: string; reason: string }>;
}

export interface DataSnapshot {
  totalAssets: number;
  assetsWithCriticalIssues: number;
  totalDocuments: number;
  totalProcedures: number;
  totalPermits: number;
  totalActiveAlerts: number;
  complianceGlobalAtMoment: number;
}

export interface GeneratePackageInput {
  periodFrom: string;
  periodTo: string;
  locationIds?: string[];
  assetTypeIds?: string[];
  reason: string;
  /* Optional subset of report codes (REPORT_FILES.REPORTS[*].code). */
  includedReports?: string[];
}

export interface ValidationResult {
  valid: boolean;
  expectedFiles: number;
  actualFiles: number;
  hashMismatches: string[];
  missingFiles: string[];
  extraFiles: string[];
  packageSignatureMatches: boolean;
}

@Injectable()
export class AuditPackageService {
  private readonly logger = new Logger(AuditPackageService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly rlsService: RlsService,
    private readonly storage: StorageService,
    private readonly assetCompliance: AssetComplianceReportGenerator,
    private readonly ackCoverage: AcknowledgmentCoverageReportGenerator,
    private readonly workPermits: WorkPermitsReportGenerator,
    private readonly alertsHistory: AlertsHistoryReportGenerator,
    private readonly exceptionsAudit: ExceptionsAuditReportGenerator,
    private readonly statusChanges: AssetStatusChangesReportGenerator,
    private readonly qrInventory: AssetQrInventoryReportGenerator,
  ) {}

  /* ---- Main entrypoint ----------------------------------------- */

  async generatePackage(companyId: string, userId: string, dto: GeneratePackageInput) {
    const t0 = Date.now();

    const [company, user] = await Promise.all([
      this.prisma.company.findUnique({
        where: { id: companyId },
        select: { id: true, name: true, taxId: true },
      }),
      this.prisma.user.findUnique({
        where: { id: userId },
        select: { id: true, email: true, firstName: true, lastName: true },
      }),
    ]);
    if (!company) throw new NotFoundException('Empresa no encontrada.');
    if (!user) throw new NotFoundException('Usuario no encontrado.');

    const auditPackageId = randomUUID();
    const generatedAt = new Date();
    const fullName = `${user.firstName ?? ''} ${user.lastName ?? ''}`.trim() || user.email;

    /* 1. Generate all 7 reports in parallel. Each one is wrapped
       in its own try/catch — we do NOT abort the package on a
       single failure (auditors prefer "6 of 7 with one note" over
       "nothing"). */
    const reportFilter = dto.includedReports?.length ? new Set(dto.includedReports) : null;
    const reports = await this.buildAllReports(
      companyId,
      {
        periodFrom: dto.periodFrom,
        periodTo: dto.periodTo,
        locationIds: dto.locationIds,
        assetTypeIds: dto.assetTypeIds,
      },
      reportFilter,
    );
    const failedReports = reports
      .filter((r) => r.buffer === null)
      .map((r) => ({ name: r.fileName, reason: r.error ?? 'Error desconocido' }));

    /* 2. Snapshot the live KPIs at generation time. The auditor
       sees the exact numbers Excelsia was showing at this
       instant — useful for matching against the per-report
       totals. */
    const snapshot = await this.getDataSnapshot(companyId);

    /* 3. Build the manifest from the *successful* report files
       only; the cover PDF lists the failed ones prominently so
       the auditor knows. */
    const successfulReports = reports.filter((r) => r.buffer !== null) as Array<
      ReportProduce & { buffer: Buffer }
    >;

    /* Cover + legal go in first; their hashes are computed below
       once we have the full file list. */
    const legalPdf = await this.buildLegalFrameworkPdf();
    const partialFileList: Array<{
      name: string;
      buffer: Buffer;
      rowsCount: number | null;
    }> = [
      ...successfulReports.map((r) => ({
        name: r.fileName,
        buffer: r.buffer,
        rowsCount: null,
      })),
      { name: REPORT_FILES.LEGAL, buffer: legalPdf, rowsCount: null },
    ];

    /* The cover PDF embeds the manifest hashes, so we have to
       generate it AFTER the others. We compute the manifest twice:
       a draft (no cover hash) for the cover renderer, then the
       final manifest that includes the cover's own hash. The
       packageSignature in the final manifest covers all files,
       cover included. */
    const draftManifest = this.buildManifest({
      auditPackageId,
      generatedAt,
      generatedBy: { id: user.id, email: user.email, name: fullName },
      company: { id: company.id, name: company.name, rut: company.taxId },
      scope: {
        period: {
          from: new Date(dto.periodFrom).toISOString(),
          to: new Date(dto.periodTo).toISOString(),
        },
        locations: dto.locationIds?.length ? dto.locationIds : 'all',
        assetTypes: dto.assetTypeIds?.length ? dto.assetTypeIds : 'all',
        reason: dto.reason,
      },
      files: partialFileList,
      snapshot,
      failedReports,
    });

    const coverPdf = await this.buildCoverPdf(
      company,
      { id: user.id, email: user.email, name: fullName },
      dto,
      draftManifest,
    );

    /* Final manifest — same shape, now includes the cover. */
    const finalManifest = this.buildManifest({
      auditPackageId,
      generatedAt,
      generatedBy: { id: user.id, email: user.email, name: fullName },
      company: { id: company.id, name: company.name, rut: company.taxId },
      scope: draftManifest.scope,
      files: [{ name: REPORT_FILES.COVER, buffer: coverPdf, rowsCount: null }, ...partialFileList],
      snapshot,
      failedReports,
    });

    /* 4. ZIP — order is cover → legal → manifest → reports. The
       ZIP itself is what the auditor downloads. */
    const zipBuffer = await this.composeZip(
      coverPdf,
      legalPdf,
      finalManifest,
      successfulReports.map((r) => ({ name: r.fileName, buffer: r.buffer })),
    );

    /* 5. Persist. Try MinIO first; fall back to DB blob if
       storage isn't configured. */
    let filePath: string | null = null;
    let fileData: Buffer | null = null;
    if (this.storage.isConfigured()) {
      const key = `operations/audit-packages/${companyId}/${auditPackageId}/package.zip`;
      try {
        await this.storage.uploadFile(AUDIT_PACKAGE_BUCKET, key, zipBuffer, 'application/zip');
        filePath = key;
      } catch (err) {
        this.logger.warn(
          `MinIO upload failed; falling back to DB blob: ${err instanceof Error ? err.message : err}`,
        );
        fileData = zipBuffer;
      }
    } else {
      fileData = zipBuffer;
    }

    const expiresAt = new Date(generatedAt);
    expiresAt.setDate(expiresAt.getDate() + PACKAGE_TTL_DAYS);

    /* Prisma's Bytes column expects Uint8Array<ArrayBuffer>; the
     * TS lib widens Uint8Array's generic to ArrayBufferLike (which
     * includes SharedArrayBuffer), so we cast through unknown after
     * copying into a fresh ArrayBuffer. The runtime value is exactly
     * what Prisma wants. */
    let fileDataPayload: Uint8Array<ArrayBuffer> | null = null;
    if (fileData !== null) {
      const ab = new ArrayBuffer(fileData.byteLength);
      const view = new Uint8Array(ab);
      view.set(fileData);
      fileDataPayload = view as unknown as Uint8Array<ArrayBuffer>;
    }

    const persisted = await this.rlsService.executeWithRls(companyId, userId, (tx) =>
      tx.auditPackage.create({
        data: {
          id: auditPackageId,
          companyId,
          generatedAt,
          generatedBy: userId,
          scope: finalManifest.scope as unknown as Prisma.InputJsonValue,
          manifest: finalManifest as unknown as Prisma.InputJsonValue,
          packageSignature: finalManifest.packageSignature,
          filePath,
          fileData: fileDataPayload,
          fileSize: zipBuffer.length,
          reason: dto.reason,
          expiresAt,
        },
        select: {
          id: true,
          companyId: true,
          generatedAt: true,
          generatedBy: true,
          scope: true,
          manifest: true,
          packageSignature: true,
          filePath: true,
          fileSize: true,
          reason: true,
          expiresAt: true,
          createdAt: true,
        },
      }),
    );

    this.logger.log(
      `Generated audit package ${auditPackageId} for ${company.name} in ${Date.now() - t0}ms (${zipBuffer.length} bytes, ${successfulReports.length}/${reports.length} reports OK)`,
    );

    return persisted;
  }

  /* ---- List + retrieve ----------------------------------------- */

  async findAll(
    companyId: string,
    filters: {
      fromDate?: string;
      toDate?: string;
      generatedBy?: string;
      page?: number;
      limit?: number;
    } = {},
  ) {
    const page = Math.max(1, filters.page ?? 1);
    const limit = Math.min(100, Math.max(1, filters.limit ?? 20));

    const where: Prisma.AuditPackageWhereInput = { companyId };
    if (filters.fromDate || filters.toDate) {
      where.generatedAt = {};
      if (filters.fromDate) where.generatedAt.gte = new Date(filters.fromDate);
      if (filters.toDate) where.generatedAt.lte = new Date(filters.toDate);
    }
    if (filters.generatedBy) where.generatedBy = filters.generatedBy;

    const [data, total] = await Promise.all([
      this.prisma.auditPackage.findMany({
        where,
        select: {
          id: true,
          generatedAt: true,
          generatedBy: true,
          scope: true,
          fileSize: true,
          reason: true,
          expiresAt: true,
          packageSignature: true,
          /* Return only the small file-list summary — the full
             manifest is on /packages/:id. */
        },
        orderBy: { generatedAt: 'desc' },
        skip: (page - 1) * limit,
        take: limit,
      }),
      this.prisma.auditPackage.count({ where }),
    ]);

    /* Resolve generator names in one pass. */
    const userIds = Array.from(new Set(data.map((d) => d.generatedBy)));
    const users = userIds.length
      ? await this.prisma.user.findMany({
          where: { id: { in: userIds } },
          select: { id: true, firstName: true, lastName: true, email: true },
        })
      : [];
    const userById = new Map(users.map((u) => [u.id, u]));

    return {
      data: data.map((d) => {
        const u = userById.get(d.generatedBy);
        const generatedByName = u
          ? `${u.firstName ?? ''} ${u.lastName ?? ''}`.trim() || u.email
          : d.generatedBy;
        const scope = d.scope as { period?: { from: string; to: string } };
        return {
          id: d.id,
          generatedAt: d.generatedAt,
          generatedBy: { id: d.generatedBy, name: generatedByName },
          period: scope.period ?? null,
          fileSize: d.fileSize,
          reason: d.reason,
          expiresAt: d.expiresAt,
          packageSignature: d.packageSignature,
        };
      }),
      total,
      page,
      limit,
      totalPages: Math.ceil(total / limit),
    };
  }

  async findOne(companyId: string, id: string) {
    const row = await this.prisma.auditPackage.findFirst({
      where: { id, companyId },
    });
    if (!row) throw new NotFoundException('Paquete de auditoría no encontrado.');
    return row;
  }

  async downloadPackage(companyId: string, id: string): Promise<Buffer> {
    const row = await this.prisma.auditPackage.findFirst({
      where: { id, companyId },
      select: { id: true, filePath: true, fileData: true },
    });
    if (!row) throw new NotFoundException('Paquete de auditoría no encontrado.');
    if (row.fileData) return Buffer.from(row.fileData);
    if (row.filePath) {
      try {
        return await this.storage.downloadFile(AUDIT_PACKAGE_BUCKET, row.filePath);
      } catch (err) {
        this.logger.error(
          `MinIO download failed for ${row.id}: ${err instanceof Error ? err.message : err}`,
        );
        throw new NotFoundException('Bytes del paquete no disponibles en almacenamiento.');
      }
    }
    throw new NotFoundException('El paquete no contiene datos.');
  }

  /* ---- Validate ------------------------------------------------ */

  async validatePackageIntegrity(uploadedZip: Buffer): Promise<ValidationResult> {
    let zip: JSZip;
    try {
      zip = await JSZip.loadAsync(uploadedZip);
    } catch {
      throw new BadRequestException('El archivo no es un ZIP válido.');
    }

    const manifestEntry = zip.file(REPORT_FILES.MANIFEST);
    if (!manifestEntry) {
      throw new BadRequestException(
        `El ZIP no contiene ${REPORT_FILES.MANIFEST}; no es un paquete de auditoría Excelsia.`,
      );
    }
    let manifest: AuditPackageManifest;
    try {
      const manifestText = await manifestEntry.async('string');
      manifest = JSON.parse(manifestText) as AuditPackageManifest;
    } catch {
      throw new BadRequestException('El MANIFIESTO.json del ZIP es ilegible.');
    }

    const expectedNames = new Set(manifest.files.map((f) => f.name));
    const actualNames = new Set(
      Object.keys(zip.files).filter((n) => !zip.files[n].dir && n !== REPORT_FILES.MANIFEST),
    );

    const missingFiles: string[] = [];
    const hashMismatches: string[] = [];

    for (const entry of manifest.files) {
      const file = zip.file(entry.name);
      if (!file) {
        missingFiles.push(entry.name);
        continue;
      }
      const bytes = await file.async('nodebuffer');
      const hash = this.computeHash(bytes);
      if (hash !== entry.sha256) {
        hashMismatches.push(entry.name);
      }
    }

    const extraFiles: string[] = [];
    for (const name of actualNames) {
      if (!expectedNames.has(name)) extraFiles.push(name);
    }

    /* Recompute the master signature from the manifest's recorded
       hashes — if the manifest itself was tampered with, this
       check catches it. */
    const expectedSignature = this.computePackageSignature(manifest.files);
    const packageSignatureMatches = expectedSignature === manifest.packageSignature;

    const valid =
      missingFiles.length === 0 &&
      hashMismatches.length === 0 &&
      extraFiles.length === 0 &&
      packageSignatureMatches;

    return {
      valid,
      expectedFiles: manifest.files.length,
      actualFiles: actualNames.size,
      hashMismatches,
      missingFiles,
      extraFiles,
      packageSignatureMatches,
    };
  }

  /* ---- Snapshot ------------------------------------------------ */

  async getDataSnapshot(companyId: string): Promise<DataSnapshot> {
    const [
      totalAssets,
      blockedAssets,
      totalDocuments,
      totalProcedures,
      totalPermits,
      totalActiveAlerts,
      docCompliance,
    ] = await Promise.all([
      this.prisma.operationalAsset.count({
        where: { companyId, isActive: true },
      }),
      this.prisma.operationalAsset.count({
        where: {
          companyId,
          isActive: true,
          status: { in: ['BLOCKED_DOCUMENTAL', 'BLOCKED_PERMIT'] },
        },
      }),
      this.prisma.documentRecord.count({
        where: { companyId, isActive: true, status: { not: 'REPLACED' } },
      }),
      this.prisma.procedure.count({
        where: { companyId, isActive: true, status: 'PUBLISHED' },
      }),
      this.prisma.permit.count({
        where: { companyId, isActive: true, status: 'APPROVED' },
      }),
      this.prisma.alertInstance.count({
        where: { companyId, status: 'ACTIVE' },
      }),
      /* Cheap global compliance proxy: % of approved docs vs total
         non-replaced. The full per-asset compliance lives in MV. */
      this.prisma.documentRecord.groupBy({
        by: ['status'],
        where: { companyId, isActive: true, status: { not: 'REPLACED' } },
        _count: { _all: true },
      }),
    ]);

    const totalNonReplaced = docCompliance.reduce((s, r) => s + r._count._all, 0);
    const approved = docCompliance.find((r) => r.status === 'APPROVED')?._count._all ?? 0;
    const compliancePct =
      totalNonReplaced === 0 ? 100 : Math.round((approved / totalNonReplaced) * 1000) / 10;

    return {
      totalAssets,
      assetsWithCriticalIssues: blockedAssets,
      totalDocuments,
      totalProcedures,
      totalPermits,
      totalActiveAlerts,
      complianceGlobalAtMoment: compliancePct,
    };
  }

  /* ---- Internal: report fan-out -------------------------------- */

  private async buildAllReports(
    companyId: string,
    scope: {
      periodFrom: string;
      periodTo: string;
      locationIds?: string[];
      assetTypeIds?: string[];
    },
    only: Set<string> | null,
  ): Promise<ReportProduce[]> {
    /* The 4 OPS-031 generators take varied filter shapes; we map
       the common scope onto each. Where a generator doesn't accept
       a location/type filter we silently drop it — the report is
       still useful, just unfiltered. */
    const tasks: Array<
      () => Promise<{
        code: string;
        fileName: string;
        label: string;
        buffer: Buffer;
      }>
    > = [];

    /* Index defs once so each `if (want(code))` block looks up its
       file metadata without a separate find() per branch. The map
       is built from the same constant the manifest references, so
       there's no chance of code drift. Key type widened to plain
       string because the lookup helper takes a string code. */
    type ReportDef = (typeof REPORT_FILES.REPORTS)[number];
    const defByCode = new Map<string, ReportDef>(REPORT_FILES.REPORTS.map((r) => [r.code, r]));
    const want = (code: string) => !only || only.has(code);
    const enqueue = (code: string, run: () => Promise<Buffer>) => {
      const def = defByCode.get(code);
      if (!def) return;
      tasks.push(async () => ({
        code: def.code,
        fileName: def.name,
        label: def.label,
        buffer: await run(),
      }));
    };

    if (want('01')) {
      enqueue('01', () =>
        this.assetCompliance.generateExcel(companyId, {
          assetTypeId: scope.assetTypeIds?.[0],
          locationId: scope.locationIds?.[0],
        }),
      );
    }
    if (want('02')) enqueue('02', () => this.ackCoverage.generateExcel(companyId, {}));
    if (want('03')) {
      enqueue('03', () =>
        this.workPermits.generateExcel(companyId, {
          startDate: scope.periodFrom,
          endDate: scope.periodTo,
        }),
      );
    }
    if (want('04')) {
      enqueue('04', () =>
        this.alertsHistory.generateExcel(companyId, {
          startDate: scope.periodFrom,
          endDate: scope.periodTo,
        }),
      );
    }
    if (want('05')) {
      enqueue('05', () =>
        this.exceptionsAudit.generateExcel(companyId, {
          startDate: scope.periodFrom,
          endDate: scope.periodTo,
        }),
      );
    }
    if (want('06')) {
      enqueue('06', () =>
        this.statusChanges.generateExcel(companyId, {
          startDate: scope.periodFrom,
          endDate: scope.periodTo,
        }),
      );
    }
    if (want('07')) enqueue('07', () => this.qrInventory.generateExcel(companyId, {}));

    /* Run sequentially to keep memory predictable. Parallel
       Promise.all could spike RSS for a large company. */
    const out: ReportProduce[] = [];
    for (const task of tasks) {
      try {
        const ok = await task();
        out.push({ ...ok, error: null });
      } catch (err) {
        const msg = err instanceof Error ? err.message : 'Error desconocido';
        this.logger.warn(`Report generation failed: ${msg}`);
        /* Emit a placeholder entry so the cover PDF can list the
           failure. The fileName / label come from the in-flight
           task — re-derive from the REPORT_FILES table by index. */
        const idx = out.length;
        const def = REPORT_FILES.REPORTS[idx];
        out.push({
          code: def?.code ?? `report-${idx}`,
          fileName: def?.name ?? `report-${idx}.xlsx`,
          label: def?.label ?? `Reporte ${idx}`,
          buffer: null,
          error: msg,
        });
      }
    }
    return out;
  }

  /* ---- Internal: PDFs ------------------------------------------ */

  private async buildCoverPdf(
    company: { id: string; name: string; taxId: string | null },
    user: { id: string; email: string; name: string },
    dto: GeneratePackageInput,
    manifest: AuditPackageManifest,
  ): Promise<Buffer> {
    return new Promise<Buffer>((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      /* ---- Page 1 — Cover ---- */
      doc
        .fontSize(10)
        .fillColor('#64748b')
        .text('EXCELSIA ERP — MÓDULO OPERACIONES', 50, 50, { align: 'left' })
        .text(`Generado: ${manifest.generatedAt}`, { align: 'right' });

      doc.moveDown(2);
      doc.fontSize(20).fillColor('#0f172a').text('PAQUETE DE AUDITORÍA', { align: 'left' });
      doc
        .fontSize(12)
        .fillColor('#475569')
        .text('Evidencia de cumplimiento — Operaciones', { align: 'left' });

      doc
        .moveTo(50, doc.y + 8)
        .lineTo(545, doc.y + 8)
        .strokeColor('#e2e8f0')
        .stroke();
      doc.moveDown(2);

      doc.fontSize(11).fillColor('#0f172a');
      doc.text('Empresa', { continued: true }).fillColor('#475569').text(`  ${company.name}`);
      doc
        .fillColor('#0f172a')
        .text('RUT', { continued: true })
        .fillColor('#475569')
        .text(`  ${company.taxId ?? '—'}`);
      doc.moveDown(0.5);
      doc
        .fillColor('#0f172a')
        .text('Generado por', { continued: true })
        .fillColor('#475569')
        .text(`  ${user.name} (${user.email})`);
      doc
        .fillColor('#0f172a')
        .text('Período', { continued: true })
        .fillColor('#475569')
        .text(`  ${manifest.scope.period.from} → ${manifest.scope.period.to}`);

      doc.moveDown();
      doc.fillColor('#0f172a').text('Alcance', { continued: false });
      doc
        .fillColor('#475569')
        .fontSize(10)
        .text(
          `Ubicaciones: ${manifest.scope.locations === 'all' ? 'todas' : manifest.scope.locations.join(', ')}`,
        )
        .text(
          `Tipos de activo: ${manifest.scope.assetTypes === 'all' ? 'todos' : manifest.scope.assetTypes.join(', ')}`,
        );

      doc.moveDown();
      doc.fontSize(11).fillColor('#0f172a').text('Razón de la auditoría');
      doc.fontSize(10).fillColor('#475569').text(dto.reason, { width: 495 });

      if (manifest.failedReports.length > 0) {
        doc.moveDown();
        doc.fontSize(11).fillColor('#b91c1c').text('⚠ Reportes que NO pudieron generarse');
        for (const f of manifest.failedReports) {
          doc.fontSize(9).fillColor('#7f1d1d').text(`  • ${f.name} — ${f.reason}`);
        }
      }

      /* ---- Page 2 — Integrity instructions ---- */
      doc.addPage();
      doc
        .fontSize(16)
        .fillColor('#0f172a')
        .text('Cómo verificar la integridad de este paquete', { align: 'left' });
      doc.moveDown();
      doc.fontSize(10).fillColor('#475569');
      doc.text('1. El archivo MANIFIESTO.json contiene el SHA-256 de cada archivo del paquete.');
      doc.text(
        '2. Recalcula el hash de cada archivo (en Linux/macOS: shasum -a 256 archivo) y compáralo con el del manifiesto.',
      );
      doc.text(
        '3. Si todos los hashes coinciden, el paquete no fue modificado desde su generación.',
      );
      doc.text(
        '4. (Opcional) En Excelsia ERP, sección "Auditoría → Validar integridad", sube este ZIP — el sistema realiza la verificación automáticamente.',
      );
      doc.moveDown();
      doc
        .fontSize(11)
        .fillColor('#0f172a')
        .text('Firma maestra del paquete (SHA-256 de los hashes concatenados):');
      doc.fontSize(8).fillColor('#1d4ed8').font('Courier').text(manifest.packageSignature);
      doc.font('Helvetica');

      doc.moveDown(1.5);
      doc.fontSize(11).fillColor('#0f172a').text('Archivos incluidos');
      const tableTop = doc.y + 6;
      doc.fontSize(9).fillColor('#0f172a');
      doc.text('Archivo', 50, tableTop);
      doc.text('Tamaño', 320, tableTop);
      doc.text('SHA-256 (primeros 16)', 400, tableTop);
      doc
        .moveTo(50, tableTop + 12)
        .lineTo(545, tableTop + 12)
        .strokeColor('#cbd5e1')
        .stroke();

      let y = tableTop + 16;
      doc.fontSize(8).fillColor('#475569');
      for (const f of manifest.files) {
        if (y > 760) {
          doc.addPage();
          y = 60;
        }
        doc.text(f.name, 50, y, { width: 260, ellipsis: true });
        doc.text(`${(f.size / 1024).toFixed(1)} KB`, 320, y);
        doc.font('Courier').text(f.sha256.slice(0, 16) + '…', 400, y);
        doc.font('Helvetica');
        y += 12;
      }

      doc.end();
    });
  }

  private async buildLegalFrameworkPdf(): Promise<Buffer> {
    return new Promise<Buffer>((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      /* ---- Cover ---- */
      doc
        .fontSize(22)
        .fillColor('#0f172a')
        .text('Marco Normativo Chileno', 50, 80, { align: 'left' });
      doc.fontSize(14).fillColor('#475569').text('Operaciones — Cumplimiento aplicable');
      doc
        .moveTo(50, doc.y + 12)
        .lineTo(545, doc.y + 12)
        .strokeColor('#e2e8f0')
        .stroke();

      doc.moveDown(2);
      doc.fontSize(10).fillColor('#475569');
      doc.text(
        'Este documento describe las normas chilenas aplicables al módulo Operaciones de Excelsia ERP, ' +
          'qué exige cada una, y cómo el sistema cubre esos requisitos. Cada sección incluye los reportes ' +
          'del paquete que evidencian cumplimiento, y un enlace a la fuente oficial (Biblioteca del Congreso ' +
          'Nacional de Chile).',
        { width: 495 },
      );

      /* ---- One section per law ---- */
      for (const law of LEGAL_FRAMEWORK_CHILE) {
        doc.addPage();
        doc.fontSize(16).fillColor('#1d4ed8').text(law.name, 50, 60);
        doc.fontSize(11).fillColor('#0f172a').text(law.fullName, { width: 495 });

        doc
          .moveTo(50, doc.y + 6)
          .lineTo(545, doc.y + 6)
          .strokeColor('#e2e8f0')
          .stroke();
        doc.moveDown(1);

        doc.fontSize(11).fillColor('#0f172a').text('¿Qué exige?');
        doc.moveDown(0.3);
        doc.fontSize(10).fillColor('#475569');
        for (const r of law.requirements) {
          doc.text(`  • ${r}`, { width: 495 });
        }

        doc.moveDown();
        doc.fontSize(11).fillColor('#0f172a').text('Cómo Excelsia lo cubre');
        doc.moveDown(0.3);
        doc.fontSize(10).fillColor('#475569');
        for (const c of law.coverage) {
          doc.text(`  • ${c}`, { width: 495 });
        }

        doc.moveDown();
        doc
          .fontSize(11)
          .fillColor('#0f172a')
          .text('Reportes en este paquete que demuestran cumplimiento');
        doc
          .fontSize(10)
          .fillColor('#1d4ed8')
          .text(law.relatedReports.map((r) => `Reporte ${r}`).join(' · '));

        doc.moveDown();
        doc.fontSize(9).fillColor('#64748b').text('Fuente oficial:');
        doc.fontSize(9).fillColor('#1d4ed8').text(law.officialSource, { link: law.officialSource });
      }

      doc.end();
    });
  }

  /* ---- Internal: manifest + ZIP -------------------------------- */

  private buildManifest(input: {
    auditPackageId: string;
    generatedAt: Date;
    generatedBy: { id: string; email: string; name: string };
    company: { id: string; name: string; rut: string | null };
    scope: AuditPackageManifest['scope'];
    files: Array<{ name: string; buffer: Buffer; rowsCount: number | null }>;
    snapshot: DataSnapshot;
    failedReports: Array<{ name: string; reason: string }>;
  }): AuditPackageManifest {
    const fileEntries: ManifestFileEntry[] = input.files.map((f) => ({
      name: f.name,
      sha256: this.computeHash(f.buffer),
      size: f.buffer.length,
      rowsCount: f.rowsCount,
    }));
    return {
      version: '1.0',
      auditPackageId: input.auditPackageId,
      generatedAt: input.generatedAt.toISOString(),
      generatedBy: input.generatedBy,
      company: input.company,
      scope: input.scope,
      files: fileEntries,
      packageSignature: this.computePackageSignature(fileEntries),
      dataSnapshot: input.snapshot,
      framework: LEGAL_FRAMEWORK_CHILE.map((l) => l.name),
      failedReports: input.failedReports,
    };
  }

  private async composeZip(
    coverPdf: Buffer,
    legalPdf: Buffer,
    manifest: AuditPackageManifest,
    reports: Array<{ name: string; buffer: Buffer }>,
  ): Promise<Buffer> {
    return new Promise<Buffer>((resolve, reject) => {
      const stream = new PassThrough();
      const chunks: Buffer[] = [];
      stream.on('data', (c: Buffer) => chunks.push(c));
      stream.on('end', () => resolve(Buffer.concat(chunks)));
      stream.on('error', reject);

      const archive = archiver('zip', { zlib: { level: 9 } });
      archive.on('error', reject);
      archive.pipe(stream);

      archive.append(coverPdf, { name: REPORT_FILES.COVER });
      archive.append(legalPdf, { name: REPORT_FILES.LEGAL });
      archive.append(JSON.stringify(manifest, null, 2), {
        name: REPORT_FILES.MANIFEST,
      });
      for (const r of reports) {
        archive.append(r.buffer, { name: r.name });
      }

      archive.finalize();
    });
  }

  private computeHash(buffer: Buffer): string {
    return createHash('sha256').update(buffer).digest('hex');
  }

  /* Master signature — SHA-256 of every file's hash concatenated.
     Stable regardless of file order because we sort by name first. */
  private computePackageSignature(files: ManifestFileEntry[]): string {
    const sorted = [...files].sort((a, b) => a.name.localeCompare(b.name));
    const concatenated = sorted.map((f) => f.sha256).join('');
    return createHash('sha256').update(concatenated).digest('hex');
  }
}
