-- OPS-033 — Auto-generated cash commitments from operational events.
-- Extends `commitments` with provenance + fulfillment columns,
-- introduces `commitment_templates` (the cost lookup table), and
-- flips `enableAutoCommitments` onto company_alert_settings as the
-- per-company kill switch.

-- ---- 1. Commitment status enum: add FULFILLED -----------
ALTER TYPE "CommitmentStatus" ADD VALUE IF NOT EXISTS 'FULFILLED';

-- ---- 2. commitments — provenance + fulfillment columns --
ALTER TABLE "commitments"
  ADD COLUMN "sourceType" TEXT,
  ADD COLUMN "sourceId" UUID,
  ADD COLUMN "sourceMetadata" JSONB,
  ADD COLUMN "isAutoGenerated" BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN "autoFulfilledAt" TIMESTAMP(3),
  ADD COLUMN "autoFulfilledBy" TEXT;

CREATE INDEX "commitments_companyId_sourceType_sourceId_idx"
  ON "commitments"("companyId", "sourceType", "sourceId");

-- ---- 3. commitment_templates ----------------------------
CREATE TABLE "commitment_templates" (
    "id" UUID NOT NULL,
    "companyId" UUID NOT NULL,
    "documentTypeId" UUID,
    "permitTypeId" UUID,
    "categoryId" UUID NOT NULL,
    "description" TEXT NOT NULL,
    "estimatedAmount" DECIMAL(18,2) NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'CLP',
    "daysBeforeExpiration" INTEGER NOT NULL DEFAULT 30,
    "isActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" UUID NOT NULL,

    CONSTRAINT "commitment_templates_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "commitment_templates_companyId_documentTypeId_idx"
  ON "commitment_templates"("companyId", "documentTypeId");
CREATE INDEX "commitment_templates_companyId_permitTypeId_idx"
  ON "commitment_templates"("companyId", "permitTypeId");

-- One template per (company, documentType) and per (company, permitType).
-- Partial uniques because documentTypeId / permitTypeId are mutually
-- exclusive — exactly one is populated per row.
CREATE UNIQUE INDEX "commitment_templates_company_doctype_unique"
  ON "commitment_templates"("companyId", "documentTypeId")
  WHERE "documentTypeId" IS NOT NULL;
CREATE UNIQUE INDEX "commitment_templates_company_permittype_unique"
  ON "commitment_templates"("companyId", "permitTypeId")
  WHERE "permitTypeId" IS NOT NULL;

ALTER TABLE "commitment_templates" ADD CONSTRAINT "commitment_templates_categoryId_fkey"
  FOREIGN KEY ("categoryId") REFERENCES "categories"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

-- RLS — same posture as every other operations table.
ALTER TABLE commitment_templates ENABLE ROW LEVEL SECURITY;
CREATE POLICY commitment_template_isolation ON commitment_templates
  USING ("companyId" = current_setting('rls.company_id', true)::uuid);

GRANT SELECT, INSERT, UPDATE, DELETE ON commitment_templates TO app_user;

CREATE TRIGGER audit_commitment_templates
  AFTER INSERT OR UPDATE OR DELETE ON commitment_templates
  FOR EACH ROW EXECUTE FUNCTION audit_trigger_function();

-- ---- 4. company_alert_settings — auto-commitments toggle
ALTER TABLE "company_alert_settings"
  ADD COLUMN "enableAutoCommitments" BOOLEAN NOT NULL DEFAULT TRUE;
